### ISSUE TITLE
combined, comprehensive kubernetes views

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2620]
This is an umbrella issue:

- [x] #1444 add DaemonSets (released in 1.3)
- [x] #2239 add StatefulSets
- [x] #2571 add CronJobs
- [x] #2552 combined view of k8s controllers
- [x] ~enable searching/filtering by controller type when in combined view~~
- [x] #2670 get rid of type selector
- [x] #2661 get rid of ReplicaSets (at least from the UI)

**Comment by rade** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scope Kubernetes View](https://trello.com/c/iJzYERG7/10-scope-kubernetes-view)

**Comment by jpellizzari** [comment]
> enable searching/filtering by controller type when in combined view, and get rid of type selector

The current convention dictates that we use the search term `controller_type:daemonset` or something similar. Maybe `node_type:`? `type:`?

**Comment by jpellizzari** [comment]
Whoops accidentally closed

**Comment by rade** [comment]
> The current convention dictates that we use the search term `controller_type:daemonset` or something similar. Maybe `node_type:`? `type:`?

Let @ekimekim decide.

**Comment by jpellizzari** [comment]
I can already search by node type since its part of the metadata fields:
![screen shot 2017-06-29 at 3 31 34 pm](https://user-images.githubusercontent.com/2802257/27713371-3dbb979e-5ce0-11e7-9987-46336df41ce1.png)

In fact, that is one of the examples. @ekimekim Maybe I am missing the requirement here?

**Comment by ekimekim** [comment]
No, it was me and @rade missing that this was already possible.

**Comment by ekimekim** [comment]
Referencing here for visibility: https://github.com/weaveworks/scope/issues/2693
Feature request to have a Volumes topology that connects to the pods/containers which access that volume. Shouldn't be too hard, and seems useful.

**Comment by rade** [comment]
> Shouldn't be too hard,

It's harder than you might think. See my comment in the issue.
